### ISSUE TITLE
Color change?

### ISSUE THREAD

**Issue by smallcolin** [jakobjohansson/dreamer-syntax#4]
![screen shot 2017-10-01 at 16 48 14](https://user-images.githubusercontent.com/24314379/31055777-55325a5c-a6c8-11e7-9871-36fab039dc0d.jpg)

Possibly have different colour for php tags as it can get a little confusing at times
Maybe even another colour for php variables also?

**Comment by jakobjohansson** [comment]
The php tags are a good idea, will probably do that. Not too sure about the variables yet though

**Comment by jakobjohansson** [comment]
Any suggestion for what color to use in php tags?

**Comment by smallcolin** [comment]
light blue or blue.  Maybe even light green.
